services:
  - type: web
    name: sgd-coraza
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
